import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Header from "@/components/shared/Header";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang='en' className='h-full'>
			<head>
				<link
					href='https://fonts.googleapis.com/css2?family=Road+Rage&display=swap'
					rel='stylesheet'
				/>
			</head>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<Header />
				<div className='mt-32'>{children}</div>
			</body>
		</html>
	);
}
